# For more information, see: https://github.com/commercialhaskell/stack/blob/master/doc/yaml_configuration.md

# Specifies the GHC version and set of packages available (e.g., lts-3.5, nightly-2015-09-21, ghc-7.10.2)
resolver: lts-9.21

# Local packages, usually specified by relative directory name
packages:
  - '.'

# Packages to be pulled from upstream that are not in the resolver (e.g., acme-missiles-0.3)
extra-deps:
  - http-types-0.12
  - http-conduit-2.3.0

# Override default flag values for local packages and extra-deps
flags:
  hoauth2:
    test: true
