default: build

watch:
	ghcid --command="cabal repl lib:hoauth2-tutorial"

repl:
	cabal repl exe:hoauth2-tutorial

start:
	cabal run exe:hoauth2-tutorial

build:
	cabal build lib:hoauth2-tutorial exe:hoauth2-tutorial
